-- Standard vim options
require("algorandpa.plugins-setup")
require("algorandpa.core.options")
require("algorandpa.core.keymaps")
require("algorandpa.core.colorscheme")
require("algorandpa.core.autocommands")
require("algorandpa.plugins.comment")
require("algorandpa.plugins.nvim-tree")
require("algorandpa.plugins.lualine")
require("algorandpa.plugins.telescope")
require("algorandpa.plugins.cmp")
require("algorandpa.lsp.lsp-setup")
require("algorandpa.lsp.autopairs")
