#!/bin/bash
# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source Omarchy's default configuration
source ~/.local/share/omarchy/default/bash/rc
# Source the modular bash configuration
source "$HOME/.config/bash/init.sh"
