# ~/.config/starship.toml
add_newline = false
# Custom Arch Linux prompt symbol
[character]
success_symbol = " "
error_symbol = " "

# Prompt for the current time
[time]
format = "[$time]($style) "
time_format = "%r"  # 12-hour time format with AM/PM
style = "bold bright-white"
disabled = false

# AWS module configuration
[aws]
format = "[$symbol($profile) - \\($region\\)]($style) "
symbol = "🅰️ "
style = "bold yellow"

# Git branch information
[git_branch]
format = "[$branch]($style) "
symbol = "🌿 "
style = "bold green"

# Git status information
[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold blue"

# Directory configuration
[directory]
truncation_length = 5
truncation_symbol = "…/"
format = "[$path]($style)[$read_only]($read_only_style) "

# Line break before the prompt
[line_break]
disabled = false

# User module
[username]
format = "[$user]($style_user) "
style_user = "bold green"
disabled = false

# Hostname module
[hostname]
format = "[$hostname]($style) "
style = "bold blue"
disabled = false

